Edit __init__.py with utf8 encode to fix TypeError
        Changed line 8:
        summary = output.split("Summary:")[-1]
    to
        summary = output.decode('utf8').split("Summary:")[-1]

    This is in response to the error:
    TypeError: a bytes-like object is required, not 'str' on line 8 of __init__.py
	
	It appears to be a change in python in version 3
    Part of the story is here:
    https://docs.python.org/3/howto/pyporting.html
    see "Text versus binary data"
    
    There is another branch that achieves this by specifying utf8 output from the subprocess.  Both work.  I am not sure of best practice.

    -RB